site_name: HIS4936 Final Project Starter
theme_dir: theme
theme: null
copyright: 'Copyright &copy; 2018 <a href="mailto:dave.a.base@gmail.com">David J. Thomas</a>'
repo_url: https://github.com/jwrae/dh-presidency-project
repo_name: 'Digital Humanities: Presidency Project'
pages:
- Home: 'index.md'
- Background: 'background.md'
- Source Analysis: 'source_analysis.md'
- Workflow: 'word_flow.md'
- Initial Findings: 'initial_findings.md'
- Problems and Possibilities: 'problems_and_possibilities.md'
- Bibliography and Credits: 'biblio_and_credits.md'
